 .gitignore                                         |  159 [32m+[m[31m-[m
 README.md                                          | 1356 [32m++++++[m[31m--[m
 ai_engine/anomaly.py                               |    4 [32m+[m[31m-[m
 ai_engine/control_safety.py                        | 1716 [32m++++++++++[m
 ai_engine/maintenance.py                           |   82 [32m+[m[31m-[m
 ai_engine/maintenance_event_manager.py             | 1538 [32m+++++++++[m
 ai_engine/optimizer.py                             | 2143 [32m++++++++++++[m
 ai_engine/production_quality.py                    | 2192 [32m++++++++++++[m
 ai_engine/quality_inspection.py                    |  550 [32m+++[m
 anomaly_injector.py                                |  309 [31m--[m
 config/scenarios.json                              |   31 [32m+[m[31m-[m
 dashboard/backend/main.py                          | 3617 [32m++++++++++++++++++++[m
 dashboard/frontend/.gitignore                      |   24 [32m+[m
 dashboard/frontend/.oxlintrc.json                  |    8 [32m+[m
 dashboard/frontend/index.html                      |   38 [32m+[m
 dashboard/frontend/package-lock.json               | 1671 [32m+++++++++[m
 dashboard/frontend/package.json                    |   25 [32m+[m
 dashboard/frontend/public/favicon.svg              |    5 [32m+[m
 dashboard/frontend/public/icons.svg                |   24 [32m+[m
 dashboard/frontend/src/App.css                     |    1 [32m+[m
 dashboard/frontend/src/App.jsx                     | 1490 [32m++++++++[m
 dashboard/frontend/src/index.css                   |  781 [32m+++++[m
 dashboard/frontend/src/main.jsx                    |   10 [32m+[m
 dashboard/frontend/vite.config.js                  |    7 [32m+[m
 data/01_factory/machine_constraints.csv            |    9 [32m+[m[31m-[m
 data/01_factory/machine_metadata.csv               |   11 [32m+[m[31m-[m
 data/02_operations/machine_metadata.csv            |   15 [32m+[m[31m-[m
 data/03_maintenance/maintenance_events.csv         |    1 [31m-[m
 data/04_grid/grid_data.csv                         |   16 [31m-[m
 data/05_scenarios/scenario_data.csv                |    8 [31m-[m
 requirements.txt                                   |   74 [32m+[m[31m-[m
 .../gazebo_factory_twin/ai_engine_node.py          | 1177 [32m++++++[m[31m-[m
 .../gazebo_factory_twin/factory_twin_node.py       | 2599 [32m++++++++++++[m[31m--[m
 .../gazebo_factory_twin/production_logger.py       |  819 [32m++++[m[31m-[m
 .../gazebo_factory_twin/scenario_manager.py        |  848 [32m++++[m[31m-[m
 .../gazebo_factory_twin/telemetry_logger.py        |  538 [32m++[m[31m-[m
 .../launch/factory_twin.launch.py                  |   16 [32m+[m[31m-[m
 .../launch/indus_twin.launch.py                    |   61 [32m+[m
 start_indus_twin.sh                                |   33 [32m+[m
 tools/anomaly_injector.py                          | 1643 [32m+++++++++[m
 40 files changed, 24245 insertions(+), 1404 deletions(-)
