from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

# Use the same Python interpreter that launched this pipeline.
# This preserves the active .venv.
PYTHON = sys.executable


# ============================================================
# PIPELINE ORDER
# ============================================================
#
# Data flow:
#
# Telemetry / Production / Grid
#          ↓
# Feature Engineering
#          ↓
# Baseline
#          ↓
# Anomaly Detection
#          ↓
# Forecasting
#          ↓
# Maintenance
#          ↓
# Production Impact
#          ↓
# Flexibility
#          ↓
# Final Decision
#
# Each step consumes outputs generated by earlier steps.
# ============================================================

STEPS = [
    (
        "Feature Engineering",
        BASE_DIR / "feature_engineering.py"
    ),
    (
        "Baseline",
        BASE_DIR / "save_baseline.py"
    ),
    (
        "Anomaly Detection",
        BASE_DIR / "anomaly.py"
    ),
    (
        "Forecasting",
        BASE_DIR / "forecasting.py"
    ),
    (
        "Maintenance Risk",
        BASE_DIR / "maintenance.py"
    ),
    (
        "Production Impact",
        BASE_DIR / "production_impact.py"
    ),
    (
        "Flexibility",
        BASE_DIR / "flexibility.py"
    ),
    (
        "Final Decision",
        BASE_DIR / "final_decision.py"
    ),
]


# ============================================================
# RUN ONE STEP
# ============================================================

def run_step(
    name: str,
    script_path: Path
) -> None:

    print("\n" + "=" * 70)
    print(f"RUNNING: {name}")
    print(f"SCRIPT : {script_path}")
    print("=" * 70)

    if not script_path.exists():

        print(
            f"ERROR: Missing script: {script_path}"
        )

        sys.exit(1)

    start_time = time.time()

    result = subprocess.run(
        [
            PYTHON,
            str(script_path)
        ],
        capture_output=True,
        text=True
    )

    # --------------------------------------------------------
    # STDOUT
    # --------------------------------------------------------

    if result.stdout:

        print(result.stdout)

    # --------------------------------------------------------
    # STDERR
    # --------------------------------------------------------

    if result.stderr:

        print(
            "----- STDERR -----"
        )

        print(
            result.stderr
        )

    # --------------------------------------------------------
    # Failure
    # --------------------------------------------------------

    if result.returncode != 0:

        duration = (
            time.time()
            - start_time
        )

        print(
            f"FAILED: {name} "
            f"({duration:.2f}s)"
        )

        sys.exit(
            result.returncode
        )

    # --------------------------------------------------------
    # Success
    # --------------------------------------------------------

    duration = (
        time.time()
        - start_time
    )

    print(
        f"COMPLETED: {name} "
        f"({duration:.2f}s)"
    )


# ============================================================
# PIPELINE
# ============================================================

def run_pipeline() -> None:

    print()
    print("=" * 70)
    print("INDUS_TWIN AI PIPELINE")
    print("=" * 70)
    print(
        f"Python: {PYTHON}"
    )
    print(
        f"AI directory: {BASE_DIR}"
    )
    print("=" * 70)

    pipeline_start = time.time()

    for step_number, (
        name,
        script_path
    ) in enumerate(
        STEPS,
        start=1
    ):

        print(
            f"\n[{step_number}/{len(STEPS)}]"
        )

        run_step(
            name,
            script_path
        )

    total_time = (
        time.time()
        - pipeline_start
    )

    print()
    print("=" * 70)
    print(
        "AI PIPELINE COMPLETED SUCCESSFULLY"
    )
    print("=" * 70)
    print(
        f"Total execution time: "
        f"{total_time:.2f}s"
    )
    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    run_pipeline()